### ISSUE TITLE
OSError: [Errno 39] Directory not empty: 'envs'

### ISSUE THREAD

**Issue by Wytamma** [Wytamma/snk#75]
Exiting gtdbtk environment...
Traceback (most recent call last):
  File "/usr/lib64/python3.9/weakref.py", line 667, in _exitfunc
    f()
  File "/usr/lib64/python3.9/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib64/python3.9/tempfile.py", line 820, in _cleanup
    cls._rmtree(name)
  File "/usr/lib64/python3.9/tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/lib64/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 667, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 667, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 667, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 6 more times]
  File "/usr/lib64/python3.9/shutil.py", line 673, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib64/python3.9/shutil.py", line 671, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'envs'

**Comment by Wytamma** [comment]
This error is coming from Snakemake -> https://github.com/snakemake/snakemake/issues/2728

**Comment by Wytamma** [comment]
Solved in https://github.com/Wytamma/snk-cli/releases/tag/v0.5.4
